DROP TABLE IF EXISTS parks;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(50) UNIQUE,
  password_digest VARCHAR NOT NULL
);

CREATE TABLE parks (
  id SERIAL PRIMARY KEY,
  name VARCHAR UNIQUE,
  description VARCHAR NOT NULL,
  user_id INTEGER REFERENCES users
);


